version: '3.9'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - memcached
    env_file:
      - ./config/environment/variables.env
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  memcached:
    image: memcached:1.6.15
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
      - -vv
volumes:
  postgres_data:
