# Generated by Django 4.0.7 on 2022-12-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('products', models.ManyToManyField(related_name='homepage_categories', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'homepage_categories',
            },
        ),
    ]
