# Generated by Django 4.0.7 on 2022-09-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('products', models.ManyToManyField(related_name='categories', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
