# Generated by Django 3.1.14 on 2022-07-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('special_status', 'Can see details.')]},
        ),
    ]
