# Generated by Django 4.0.6 on 2022-08-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cartitem_cart_alter_transaction_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='surname',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=64),
        ),
    ]
