# Generated by Django 4.0.6 on 2022-08-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='products',
            new_name='product',
        ),
    ]
