# Generated by Django 4.0.6 on 2022-08-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_price_product_description_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
