# Generated by Django 4.0.6 on 2022-08-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_products_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
