# Generated by Django 4.0.6 on 2022-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='surname',
            field=models.CharField(blank=True, default=2, max_length=24),
            preserve_default=False,
        ),
    ]
