# Generated by Django 4.0.6 on 2022-08-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
