# Generated by Django 4.0.6 on 2022-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_transaction_name_alter_transaction_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
