# Generated by Django 4.0.6 on 2022-08-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_cartitem_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
