# Generated by Django 4.0.7 on 2022-09-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_categorie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
