# Generated by Django 4.0.7 on 2022-09-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
